development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: {{project_name}}_development
  pool: 5
  username: {{username}}
  password:

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: {{project_name}}_test
  pool: 5
  username: {{username}}
  password:

production:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: {{project_name}}_production
  pool: 5
  username: {{username}}
  password:
